spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: dev
    password: dev
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop